### PR TITLE
UserRolesPermissionsTables

### LINKED ISSUE #102: Create user roles and permissions tables
We need a migration that create roles and permissions for users so we can restrict access to certain features.

See the example-app code where this was added: https://github.com/csci-2479/example-app/commit/5174b3e6ac730a8024b783a6fdfc804e991f3df9

### PR DESCRIPTION
**Pull request by ctruong1**
Migration created for user roles permissions tables

#102

### CODE REVIEW

**Comment by dshea18** [comment]
Hey Colin @ctruong1,

I am working on my admin screen currently and will be better able to review your code when I'm finished with my section, but I wanted to bring this up now just to make sure it was known.  Your branch is failing a test with the error “General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "users" add column "role_id" integer not null”. Were you leaving that value null intentionally?

V/R,
Danny

**Comment by ctruong1** [comment]
Hey @dshea18, I was following the example-app example. I'm not sure what I need to change for it to pass the test. Would I have to remove the default null?

**Comment by dshea18** [comment]
> Hey @dshea18, I was following the example-app example. I'm not sure what I need to change for it to pass the test. Would I have to remove the default null?

Hey Colin,

I found the issue. When a new user is created by breeze, it needs a role value for its role_id column. Because no default value is being provided and that field is non-nullable it crashes. I’ve been looking into solutions but I’m stuck. @oldskoolfan or @sarahdactylrex , do you have any insights?

V/R,
Danny

**Review by dshea18 — CHANGES_REQUESTED** [review]
Hey Colin,

Making the role_id nullable should fix the issue for now. 

Schema::table('users', function (Blueprint $table) {
            $table->foreignId('role_id')->nullable()->constrained();
        });

V/R,
Danny

**Comment by sarahdactylrex** [comment]
Hey guys, I added the rest of the models and whatnot but I'm stumped on this one too, I'm terrible with tables, lol. I also had the idea about inputting a default value but not sure how that would play out with it being the primary key in the role table. I'm gonna bet this is one of those easy fix things we'll see solved quickly tomorrow if none of us can solve it tonight! Sorry I'm not more helpful =(

**Comment by sarahdactylrex** [comment]
Resolved by #116

**Pull request closed without merging**
